### ISSUE TITLE
Never use the database model directly in Controller 

### ISSUE THREAD

**Issue by AbhiDashadiya** [Hasti522004/HRMSPOC#3]
You can create the DTO for taking data from the user and later on you can convet into the data model as per the requirement.

![image](https://github.com/user-attachments/assets/eb4a54db-7d48-4b09-8d71-b2001f4bfce5)

Here you are taking the Organization id from the user when he/she is try to create the organization.

**Comment by Hasti522004** [comment]
Create DTOs for all the Models, Using AutoMapper map Model and DTOs and Apply it in all the Controllers, Services and Repositories.
